-- Active: 1739211085766@@127.0.0.1@5432@digix@desafio
/*
------------------------------------------------------------------

 						        DESAFIO (24/02/25)
                                TEMA: DESAFIO
						       THIAGO OLSZEWSKI

------------------------------------------------------------------
*/
-- USING SCHEMA DESAFIO FROM DIGIX DATABASE IN POSTGRESQL

/*
    CREATING TRIGGERS FOR THE CHALLENGE
*/

-- DROP TABLE VENDAS, COMPRAS, CLIENTES, ESTOQUE, FORNECEDORES, PRODUTOS, COMPRAS_PRODUTOS, VENDAS_PRODUTOS;

-- TRIGGER FOR CHECK IF THE CLIENT NEEDS AN CPF OR CNPJ
CREATE OR REPLACE FUNCTION FN_CHECK_CLIENT_TYPE()
RETURNS TRIGGER AS $$
BEGIN
    IF LENGTH(NEW.CPF_CNPJ) = 14 THEN
        RAISE NOTICE 'CPF DETECTED: %', NEW.CPF_CNPJ;
        ELSIF LENGTH(NEW.CPF_CNPJ) = 18 THEN
            RAISE NOTICE 'CNPJ DETECTED: %', NEW.CPF_CNPJ;
    ELSE
        RAISE EXCEPTION 'THE VALUE OF CPF_CNPJ IS INVALID: LENGHT MUST BE 14 OR 18 CHARACTERS';
    END IF;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER TR_CHECK_CPF_CNPJ
BEFORE INSERT OR UPDATE ON CLIENTES
FOR EACH ROW
EXECUTE PROCEDURE FN_CHECK_CLIENT_TYPE();

-- 7.1 - TRIGGER PARA SUBTRAIR AUTOMATICAMENTE DO ESTOQUE AO VENDER
CREATE OR REPLACE FUNCTION FN_ATUALIZAR_ESTOQUE_VENDA()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE ESTOQUE SET QUANTIDADE = (QUANTIDADE - NEW.QUANTIDADE)
    WHERE FK_PRODUTO = NEW.FK_PRODUTO;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER TR_ATUALIZAR_ESTOQUE_VENDA
BEFORE INSERT OR UPDATE ON VENDAS_PRODUTOS
FOR EACH ROW
EXECUTE PROCEDURE FN_ATUALIZAR_ESTOQUE_VENDA();

-- 7.2 - TRIGGER PARA SOMAR AUTOMATICAMENTE AO ESTOQUE AO COMPRAR
CREATE OR REPLACE FUNCTION FN_ATUALIZAR_ESTOQUE_COMPRA()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE ESTOQUE SET QUANTIDADE = (QUANTIDADE + NEW.QUANTIDADE)
    WHERE FK_PRODUTO = NEW.FK_PRODUTO
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER TR_ATUALIZAR_ESTOQUE_COMPRA
BEFORE INSERT OR UPDATE ON COMPRA_PRODUTOS
FOR EACH ROW
EXECUTE PROCEDURE FN_ATUALIZAR_ESTOQUE_COMPRA();
