/*
------------------------------------------------------------------

 						        DESAFIO (24/02/25)
                                TEMA: DESAFIO
						       THIAGO OLSZEWSKI

------------------------------------------------------------------
*/
-- USING SCHEMA DESAFIO FROM DIGIX DATABASE IN POSTGRESQL

/*
    CREATING TRIGGERS FOR THE CHALLENGE
*/

-- TRIGGER FOR CHECK IF THE CLIENT NEEDS AN CPF OR CNPJ
CREATE OR REPLACE FUNCTION FN_CHECK_CLIENT_TYPE()
RETURNS TRIGGER AS $$
BEGIN
    IF LENGTH(NEW.CPF_CNPJ) = 14 THEN
        RAISE NOTICE 'CPF DETECTED: %', NEW.CPF_CNPJ;
        ELSIF LENGTH(NEW.CPF_CNPJ) = 18 THEN
            RAISE NOTICE 'CNPJ DETECTED: %', NEW.CPF_CNPJ;
    ELSE
        RAISE EXCEPTION 'THE VALUE OF CPF_CNPJ IS INVALID: LENGHT MUST BE 14 OR 18 CHARACTERS';
    END IF;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER TR_CHECK_CPF_CNPJ
BEFORE INSERT OR UPDATE ON CLIENTES
FOR EACH ROW
EXECUTE PROCEDURE FN_CHECK_CLIENT_TYPE();

